apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tanya-2-feb-1-devfile-sample-code-with-quarkus-jdok-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tanya-2-feb-1-devfile-sample-code-with-quarkus-jdok-sample
    app.kubernetes.io/part-of: tanya-2-feb-1
  name: tanya-2-feb-1-devfile-sample-code-with-quarkus-jdok-sample
  namespace: rhn-support-tshearon-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: tanya-2-feb-1-devfile-sample-code-with-quarkus-jdok-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: tanya-2-feb-1-devfile-sample-code-with-quarkus-jdok-sample
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:aa65830f7d5363a47e01e8cfd6d710ea70e812ca0d5d687958c7f11f2de3a0cd
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
