apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tanya-2-feb-1-devfile-sample-code-with-quarkus-jdok-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tanya-2-feb-1-devfile-sample-code-with-quarkus-jdok-sample
    app.kubernetes.io/part-of: tanya-2-feb-1
  name: tanya-2-feb-1-devfile-sample-code-with-quarkus-jdok-sample
  namespace: rhn-support-tshearon-tenant
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: tanya-2-feb-1-devfile-sample-code-with-quarkus-jdok-sample
    weight: 100
status: {}
